### ISSUE TITLE
Could you create a new version of "GuessPrivateKey" with a new function to add your formula?

### ISSUE THREAD

**Issue by amiwrcd** [scorta/GuessPrivateKey#10]
@scorta  Great code and I like your code especially when the search is done in certain
range of numbers with the function _"up / down"_.  I would be very grateful if you would make a new version of **"GuessPrivateKey"**.
I am testing my project now and I can’t find the right code. I found it turns out there are ranges of numbers from **_128 bits_** and these numbers
 can be used to search for private keys.
I have heard about collisions in tunnels piercing the space of hash functions.
Could you make it so that when I run **"GuessPrivateKey"** I can add certain formulas?
For example, the simplest formula for multiplying two unknown values ​​containing **_128 bits_**
The formula is this:
` M * L = X * G (secp256k1) = PubKey`
**M** and **L** are unknown numbers, but the advantage is that both are in a certain range of numbers.
Is it possible to configure **"GuessPrivateKey"** to add this formula and do a search in a specific range of numbers?
I would really appreciate you! I appreciate your work!

```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

```
M * L = X * G( sec256k1) = PubKey


M = 5FFDF9E967A054B02E0C56CDCF816A98
L = 45C42EF3369B5F069C57B4FF54F307F1


X = 1A29046A15178BDFC63350AFB46868F7A4ECDD7315EEC3B827F3D4A6F1078118

PubKey = 0345E6077F20C44840C7AF1F4EA1C5116E02299975698840B26F15E6172C8DAD27

```


```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

**Comment by scorta** [comment]
Thanks for your interest, but I don't have time to work on this anymore. Currently, this program use bitcoinj to generate wallet address, so there's no way to make what you want.
