### ISSUE TITLE
Potential good idea

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoins** [scorta/GuessPrivateKey#11]
Hello,

How are you doing my friend?? I hope you are well...

I think I found a interesting idea on Github have a look at this repo...https://github.com/ipsBruno/brute-force-seed-bitcoin

It is a fantastic idea...only the javascript doesn't work proper...and unfortunatelly the dev doesn't respond. I want to ask you to have a look at it and fork this idea with a proper working javascript.

Like to learn from you.

Cheers Satoshi

**Comment by SatoshiNakamotoBitcoins** [comment]
@scorta Which I can see there is a problem with installing the package blockchain.info/blockexplorer with Linux with the command:

npm install blockchain.info/blockexplorer

I run into an error...

**Comment by amiwrcd** [comment]
@SatoshiNakamotoBitcoins Hello! I have a huge list of 500 million hex private keys. I need to find one needed private key to which I know the public key. Please tell me if there is a program that finds the right private key?  need to specify one public key for the search, and when  find the desired private key, the program should stop and save this private key in a new document. Please tell me if there is such a program?

**Comment by scorta** [comment]
@SatoshiNakamotoBitcoins, sorry, but I don't have time to work on this project.

**Comment by SatoshiNakamotoBitcoins** [comment]
@amiwrcd When the public key is known...the best way to crack it is with the Pollord-Kangaroo method...have a look at the repo's of Telariust...https://github.com/Telariust he has 3 variants at the moment...a Python multi-core method...a C99 method (written in C) and a method based on the vanitygen method...in the near future GPU support will follow...to be most effictive to search with this method is to know the keyspace; for example this method is common used to crack one of the bitcoin puzzles with know public key and keyspace...so 110 bits, 115 bits, 120 bits...etc...when you don't know the keyspace you have to search in the whole keyspace of 256 bits...in that way it will not be feasible to crack even with an high multi power GPU grid...

When you want to quick search for the 500 million hex private keys the best app is brainflayer...have a look at this repo...https://github.com/ryancdotorg/brainflayer you can build this with Linux and to apply the app properly to search for the RAW private hex key input you have to apply a few FLAGS...you need the -t priv and -x FLAG  for searching for raw private key input...also you have to determine if the public key is uncompressed or compressed...is the public key starting with 04 that means uncompressed and than you also have to apply FLAG -u is the public key starting with 02 or 03 than it is compressed, if this is the case you have to apply flag -c instead -u....that public key you can convert to the BTC address and hex160 of it... with this tool...https://iancoleman.io/bitcoin-key-compression/ with that hex160 you have to make a bloomfilter (read the repo info) only for that address...I also advise you to make a .bin file (read the repo info) to filter out the FALSE positives...ofcourse you want the output to a file in case there is a BINGO...you can do this with flag -o for example -o output.txt and we need an input flag with -i (regarding your list of 500 million hex private keys) for example -i hex.txt...an example and result of a command which you have to put in the Linux CLI could be:

./brainflayer -v -b example.blf -i hex.txt -o output.txt -u -t priv -x -f example.bin

Brainflayer is running on CPU and is not multithreaded...but is written in C what means depending on your CPU it will search for 40.000 - 100.000 keys pro second...so it will not take long to look through this 500 million hex list...

Cheers Satoshi

**Comment by SatoshiNakamotoBitcoins** [comment]
@scorta Thank you for your reply my friend!
