### ISSUE TITLE
SLF4J Error, But searching why

### ISSUE THREAD

**Issue by Bronxanarchy** [scorta/GuessPrivateKey#2]
Searching keys for Bitcoin address(es) from file bit.txt with 4 thread(s)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Start importing list Bitcoin address(es)

**Comment by scorta** [comment]
Do not worry, it is just an harmless error from the library bitcoinj. The program will still run fine.
