### ISSUE TITLE
if find

### ISSUE THREAD

**Issue by Bronxphoneix** [scorta/GuessPrivateKey#3]
hi scorta, this app if find bitcoin ? how to warn ? or write txt file ? how know it

**Comment by scorta** [comment]
Hi, if found a key, the program will print info to a file, which has the same name to that WIF key.
Eg. if it found the key "L59eMgqKqxCGXrDWhGwVBZbQBra482LRLzyAj6g5CGKdq6ABCvXz", it will create a file name "L59eMgqKqxCGXrDWhGwVBZbQBra482LRLzyAj6g5CGKdq6ABCvXz.txt" and write these info into it:
````
1zJBmcSDHZ97Sjm6TmtM5M7ZdPzuiBABm //address
L59eMgqKqxCGXrDWhGwVBZbQBra482LRLzyAj6g5CGKdq6ABCvXz //key in WIF format
EC9B83954E3E5001E34B02A1705779D2B59264BB54784815B3AA3EBC10C622F0 //key in HEX format
````
So if you find a new .txt file in the same folder with this program, you have found a wallet!

Note: if it cannot create file(s), it will print these info into the screen.
Cheer.
