### ISSUE TITLE
GuessPrivateKey GPU version

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoins** [scorta/GuessPrivateKey#5]
@scorta Hello Mate...how are you?? I hope your well!

Do you have any plans to make a GuessPrivateKey GPU version (OCL and CUDA) in the near future.

I like your project, on GPU it will be even better...

Like to learn from you!

Cheers

**Comment by scorta** [comment]
@SatoshiNakamotoBitcoins Hi, thanks. I'm struggle at work & study, so no time for this project. 

I think you should stop wasting time on this. Even if you can check a billion keys/second (which is a lot of Ndivia Titan V), it still would take you 3 671 743 063 080 802 746 815 416 825 491 118 336 290 905 145 409 708 398 004 109 years to check all the Bitcoin keys.

Just stop this. Mine altcoin / shitcoin is much more profit. Cheer :D

**Comment by SatoshiNakamotoBitcoins** [comment]
@scorta Hello my friend long time no hear...I'm sorry to hear you struggling at work and study. I hope this struggle will pay off in the near future. And will bring you happiness!

Ofcourse mathematically your right...

Thnx for getting back to me.

Cheers mate!!

**Comment by scorta** [comment]
Thanks, wish you all the best :D
