### ISSUE TITLE
jar file missing

### ISSUE THREAD

**Issue by su314ka** [scorta/GuessPrivateKey#7]
jar file is missing.

**Comment by scorta** [comment]
Which jar? The release is here: https://github.com/scorta/GuessPrivateKey/releases
For bitcoinj, come here: https://search.maven.org/remotecontent?filepath=org/bitcoinj/bitcoinj-core/0.15/bitcoinj-core-0.15.jar

**Comment by su314ka** [comment]
found it. thanks
